Repository alphagov/pay-tech-docs, pull requests merged in 2019-01, with the labels that each got.

#257 State that the amount is a number
  source/payment_flow/index.html.md.erb
Labels: does not need writer review, merge when ready, trivial

#222 Language/style/flow improvements to 'Making payments' section
  source/making_payments/index.html.md.erb
Labels: does not need writer review, merge when ready, needs SME review

#262 Amend heading structure to comply with accessibility requirements
  source/account_structure/index.html.md.erb
  source/optional_features/custom_branding/index.html.md.erb
  source/testing_govuk_pay/index.html.md.erb
Labels: does not need writer review, merge when ready, needs SME review

#263 Add content stating that minimum payment amount is one pence.
  source/making_payments/index.html.md.erb
  source/payment_flow/index.html.md.erb
Labels: needs SME review, trivial

#264 Disable billing address collection
  source/integrate_with_govuk_pay/index.html.md.erb
Labels: merge when ready
