Repository alphagov/pay-tech-docs, pull requests merged in 2019-08, with the labels that each got.

#306 Update documentation on Direct Debit mandate and payment statuses
  source/direct_debit/index.html.md.erb
Labels: do not merge, needs SME review

#312 Remove unneeded items from 'Merchant Channel' events list
  source/switching_to_live/set_up_a_live_worldpay_account/index.html.md.erb
Labels: do not merge, does not need writer review

#311 Remove 'From August 2019' on Direct Debit page
  source/direct_debit/index.html.md.erb
Labels: does not need writer review

#313 PP-5519 Update Docs With New P-Codes
  source/api_reference/index.html.md.erb
Labels: needs writer review

#314 Update digital wallets documentation
  source/optional_features/digital_wallets/index.html.md.erb
Labels: do not merge, needs SME review, needs writer review
